---
# https://ci.appveyor.com/project/nodakai/python-win-behavior

environment:
  matrix:
    - PYTHON: C:/Python27-x64
    - PYTHON: C:/Python36-x64

build: off

before_test:
  - echo %PYTHON%
  - "%PYTHON%/python.exe -V"

test_script:
  - dir
  - echo testing...
  - "%PYTHON%/python.exe main.py"
  - echo tested.
  - dir
